"""fix issues

Revision ID: 6f01e351fb59
Revises: c98963c32f7c
Create Date: 2025-08-26 12:46:02.473406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '6f01e351fb59'
down_revision: Union[str, Sequence[str], None] = 'c98963c32f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger_entries', 'inning_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger_entries', 'inning_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###