"""add characters to game players

Revision ID: 99a223b99e88
Revises: 594559cf1cd3
Create Date: 2025-08-27 00:01:53.952046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '99a223b99e88'
down_revision: Union[str, Sequence[str], None] = '594559cf1cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_players', sa.Column('character', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_players', 'character')
    # ### end Alembic commands ###