"""add lifetime tables

Revision ID: c98963c32f7c
Revises: a3c2e5956a12
Create Date: 2025-08-26 12:40:15.374364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c98963c32f7c'
down_revision: Union[str, Sequence[str], None] = 'a3c2e5956a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lifetime_totals',
    sa.Column('net_dollars', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('misses', sa.Integer(), nullable=False),
    sa.Column('amendments', sa.Integer(), nullable=False),
    sa.Column('biggest_pot_won', sa.Integer(), nullable=False),
    sa.Column('picks_total', sa.Integer(), nullable=False),
    sa.Column('picks_k', sa.Integer(), nullable=False),
    sa.Column('picks_g', sa.Integer(), nullable=False),
    sa.Column('picks_f', sa.Integer(), nullable=False),
    sa.Column('picks_d', sa.Integer(), nullable=False),
    sa.Column('picks_t', sa.Integer(), nullable=False),
    sa.Column('picks_n', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('player_game_stats',
    sa.Column('net_dollars', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('misses', sa.Integer(), nullable=False),
    sa.Column('amendments', sa.Integer(), nullable=False),
    sa.Column('biggest_pot_won', sa.Integer(), nullable=False),
    sa.Column('picks_total', sa.Integer(), nullable=False),
    sa.Column('picks_k', sa.Integer(), nullable=False),
    sa.Column('picks_g', sa.Integer(), nullable=False),
    sa.Column('picks_f', sa.Integer(), nullable=False),
    sa.Column('picks_d', sa.Integer(), nullable=False),
    sa.Column('picks_t', sa.Integer(), nullable=False),
    sa.Column('picks_n', sa.Integer(), nullable=False),
    sa.Column('accuracy_pct', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['game_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_game_stats')
    op.drop_table('user_lifetime_totals')
    # ### end Alembic commands ###